Fix Earley parser stack overflow issue
palle-k/Covfefe pull request #12
Opened 2021-11-03 21:06 UTC by mikolasstuchlik

This pull request solves partially the https://github.com/palle-k/Covfefe/issues/11 issue. I can not close the issue outright, becaue CYK parser has still stack overflow issue present.

The new algorythm might be slower than the original recursive approach, but is not constrained by the length of the parsed sentence.

2021-11-04 13:05 UTC, mikolasstuchlik commented
Turns out, the parser stack-overflows in another function.
<img width="1406" alt="Snímek obrazovky 2021-11-04 v 14 02 07" src="https://user-images.githubusercontent.com/42004728/140318203-661514d1-1abe-4a2c-97cf-3010e3571f0d.png">

The test `testErleyStackOverflow` was modified to use 10000 long word and failed after 46 minutes 15 seconds of runtime.

2021-11-04 19:46 UTC, mikolasstuchlik commented
I have been able to solve the `explode` recursion. I have also profiled the program and found out, that the major bottleneck was in linear iteration through a Set instance. I have changed the Set to Array, reducing the run time for 10000 items test from 46 minutes down to < 4 minutes.

I would like to request a review. I have decided not to add an inline documentation. Let me know what pars of the code you would like to see documented. All the machines have the same architecture.

2021-11-04 20:43 UTC, mikolasstuchlik commented
Unfortunately, I have observed another issue related to recursion: all other recursive functions :/

When working on Linux, the `syntaxTree.description.count` was crashing due to `map` function stack overflow. I'm not going to solve the issue yet from two reasons:
 - I don't need the `syntaxTree.description` since I wont be able to generate such a magnificently big image (`dot` kept crashing on me even for 1000 letters long word anyway).
 - In case I would absolutely need the `syntaxTree.description` output, the program completed when usign `-c release` configuration.

Since I am now able to prototype in a reasonable time, I don't need to address the issue right now. If the PR is accepted, maybe I'll address it in the future.

2021-11-11 14:32 UTC, palle-k requested changes

2021-11-11 14:32 UTC, palle-k commented on Sources/Covfefe/SyntaxTree.swift
> +	private enum ExplostionStackFrame {
Typo in Explosion

2021-11-11 14:32 UTC, palle-k commented on Sources/Covfefe/SyntaxTree.swift
> +	/// Filters the tree by removing all leafs if the given predicate is false
Please use leaves as the plural of leaf.

2021-11-11 14:32 UTC, palle-k commented on Tests/CovfefeTests/PerformanceTests.swift
> +	func testErleyStackOverflow() {
Fix typo in Earley

2022-02-23 16:24 UTC, mikolasstuchlik commented
@palle-k Hi, can we merge this? :)

2022-02-23 16:37 UTC, palle-k approved these changes

2022-02-23 16:38 UTC, merged